<?php

//namespace Drupal\mm;

use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;
use Drupal\Core\Entity\EntityInterface;
//use Drupal\node\Plugin\Core\Entity\NodeInterface;




//$vk_crosspost = '';

function crosspost($node){
  
  $linc_post = 'https://api.vk.com/method/wall.post?owner_id=' . 
\Drupal::config('mm.settings')->get('mm.group') .
'&friends_only=' .
'' .
'&from_group=' .
'0' .
'&message=' .
$node->getTitle() .
'&attachments=' .
'' .
'&access_token=' .
\Drupal::config('mm.settings')->get('mm.token');



$client = \Drupal::httpClient();
$request = $client->get($linc_post);
$response = $request->getBody();

return $linc_post;
}



function mm_node_presave(NodeInterface $node) {
/*
$body = $node->get('body')->value;
$newbody = $body + 'my-content';
$node->set('body',$newbody);
*/
 
  if ($node->bundle() == 'article') {
   $vk_crosspost = $node->get('field_me')->value;
   if($vk_crosspost == null){
   $node->set('body','vk-crosspost is null');
    } else {
       if ($vk_crosspost == true){
       // $func = 'crosspost';
        //$func($node);
        $my_content = crosspost($node);
        $node->set('body',$node->get('body')->value .'vk-crosspost is true' . $my_content );
       } else {
         $node->set('body','vk-crosspost is false');
         }
      }

     
  } 
}

//var_dump($vk_crosspost);
//echo 'vot-vot';

















// если поле существует и истина делаем кросспост статьи
/*
function mm_node_presave(NodeInterface $node) {

  if ($node->bundle() == 'article' and $node->hasField('my_logic_field') and $node->get('my_logic_field')->value) {
   

  $linc_post = 

'https://api.vk.com/method/wall.post?owner_id=' . 
\Drupal::config('mm.settings')->get('mm.group') .
'&friends_only=' .
'' .
'&from_group=' .
'0' .
'&message=' .
$node->getTitle() .
'&attachments=' .
'' .
'&access_token=' .
\Drupal::config('mm.settings')->get('mm.token');



//$zapros = \Drupal::request()->query->get($linc_post);
} else {
$linc_post = 'nixrena';
}
   

}

var_dump($linc_post);
echo 'vot-vot';


function hook_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity instanceof ContentEntityInterface && $entity->isTranslatable()) {
    $route_match = \Drupal::routeMatch();
    \Drupal::service('content_translation.synchronizer')->synchronizeFields($entity, $entity->language()->getId(), $route_match->getParameter('source_langcode'));
  if($entity->bundle() == 'node'){
   $node = $entity; 
   if ($node->bundle() == 'article' and $node->get('my_logic_field')->value) {
   

    $linc_post = 
'https://api.vk.com/method/wall.post?owner_id=' . 
\Drupal::config('mm.settings')->get('mm.group') .
'&friends_only=' .
'' .
'&from_group=' .
'0' .
'&message=' .
$node->getTitle() .
'&attachments=' .
'' .
'&access_token=' .
\Drupal::config('mm.settings')->get('mm.token');

$zapros = \Drupal::request()->query->get($linc_post);
var_dump($zapros);
  }  


  }
 }
}


*/











